<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Unified Inviter Component

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved.
WWW: http://www.octazen.com
********************************************************************************/
//////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////
if (!defined('_OZ_INVITER')) exit();

global $_OZINVITER_CALLBACKS;
$func = $_OZINVITER_CALLBACKS['get_invite_message']	;
$msg = $func(NULL,NULL,NULL);
//$msg = oz_get_invite_message();
$url = $msg['url'];
$title = $msg['subject'];
//$text_body = str_replace('{PERSONALMESSAGE}','',$msg['text_body']);
$text_body = '';

function oz_render_bookmark($id,$name,$shareurl,$url,$title,$text_body)
{
	$u = str_replace(
		array('{URL}','{TITLE}','{MESSAGE}'), 
		array(urlencode($url),urlencode($title),urlencode($text_body)),
		$shareurl);
	return '<div class="oz_bookmark_link oz_bookmark_'.$id.'"><a href="'.$u.'" target="_blank"><span>'.htmlentities($name).'</span></a></div>';
}

?>
<div class="oz_header">
<table cellpadding="0" cellspacing="0" border="0" width="100%"><tr>
<td align="left"><span id="oz_header_label">{{BOOKMARK_TITLE}}</span></td>
<td align="right"><a href="#" onclick="ozStartAgain();return false;">{{START_AGAIN}}</a></td>
</tr></table>
</div>

<div id="ozpanel_bookmark">
  <div>{{BOOKMARK_SELECT}}</div>
  <br/>
<?php
echo oz_render_bookmark('facebook','Facebook',	'http://www.facebook.com/sharer.php?u={URL}&t={TITLE}', $url,$title,$text_body);
echo oz_render_bookmark('myspace','MySpace', 	'http://www.myspace.com/Modules/PostTo/Pages/?l=3&u={URL}&t={TITLE}&c={MESSAGE}', $url,$title,$text_body);
echo oz_render_bookmark('twitter','Twitter',	'http://twitter.com/home/?status={URL}', $url,$title,$text_body);
echo '<div class="oz_separator"></div>';
echo oz_render_bookmark('digg','Digg',			'http://digg.com/submit?phase=2&url={URL}&title={TITLE}', $url,$title,$text_body);
echo oz_render_bookmark('reddit','Reddit',		'http://reddit.com/submit?url={URL}&title={TITLE}', $url,$title,$text_body);
echo oz_render_bookmark('delicious','del.icio.us',	'http://del.icio.us/post?url={URL}&title={TITLE}', $url,$title,$text_body);
echo oz_render_bookmark('stumbleupon','StumbleUpon',	'http://www.stumbleupon.com/submit?url={URL}&title={TITLE}', $url,$title,$text_body);

?>

  <br/>
  <br/>
  <div>{{BOOKMARK_SENDTHISLINK}}</div>
  <br/>
  <form name="ozform_bookmark" style="margin:0px">
<?php echo ozi_render_form_snippet(); ?>
  <input type="text" name="oz_link" value="<?php echo htmlentities($url) ?>" class="oz_copy_text oz_field_input"/>
  </form>
  <br/>

</div>
