<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Unified Inviter Component

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved.
WWW: http://www.octazen.com
********************************************************************************/

//////////////////////////////////////////////////////////////////////////
//Parameters
//	oz_recipients
//		Array of contacts.
//////////////////////////////////////////////////////////////////////////
if (!defined('_OZ_INVITER')) exit();
?>

<div class="oz_header">
  <table cellpadding="0" cellspacing="0" border="0" width="100%">
    <tr>
      <td align="left"><span id="oz_header">{{FINISHED_TITLE}}</span></td>
      <td align="right"><a href="#" onclick="ozStartAgain2();return false;">{{START_AGAIN}}</a></td>
    </tr>
  </table>
</div>

<div id="ozpanel_finished">
  <?php
$recipients = isset($_REQUEST['oz_recipients']) ? $_REQUEST['oz_recipients'] : array();
if (count($recipients)>0)
{
	echo oz_text('FINISHED_SENT_TO');
	echo '<ul>';
	foreach ($recipients as $r) 
		echo '<li>'.htmlentities($r).'</li>';
	echo '</ul>';
}
else
{
	echo oz_text('FINISHED_SENT');
}

?>
  <br/>
  <br/>
  {{FINISHED_HAVE_MORE_FRIENDS}} <a href="#" onclick="ozStartAgain2();return false;">{{FINISHED_INVITE_THEM}}</a>
</div>
<script type="text/javascript">
ozNotifyViewChange('finished');
</script>