<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Unified Inviter Component

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved.
WWW: http://www.octazen.com
********************************************************************************/

//////////////////////////////////////////////////////////////////////////
//Takes in parameter from $_POST
//
//oz_service (optional)
//	Contains the service ID if we're to jump straight to login form
//
//oz_auth_login (optional)
//	Contains the user auth ID that is to be prefilled
//
//////////////////////////////////////////////////////////////////////////
if (!defined('_OZ_INVITER')) exit();

//Set defaults
//if (!isset($_REQUEST['oz_service'])) $_REQUEST['oz_service']='';
if (!isset($_REQUEST['oz_auth_login'])) $_REQUEST['oz_auth_login']='';

global $oz_option_count;
$oz_option_count = 0;
function oz_render_service_option($id,$name) {
	global $oz_option_count;
	$skiptest = strpos($id,'file')!==FALSE || $id=='manual' || $id=='bookmark';
	if (!ozi_get_config('facebook_classicmode',FALSE)) $skiptest=$skiptest?true:$id=='is_facebook';
	$inviter = isset($_REQUEST['oz_inviter'])?$_REQUEST['oz_inviter']:NULL;
	if (($inviter!==NULL && $inviter->is_service_supported($id)) || empty($id) || $skiptest) {
		$s = '<option value="'.htmlentities($id).'"';
		if ($id==$_REQUEST['oz_service']) $s.=' selected="selected"';
		$s .= '>'.htmlentities($name).'</option>';
		$oz_option_count++;
		return $s;
		//return oz_render_service_option2($id,$name,$loginpanel);
	}
	else {
		return '';
	}
}

?>

<div class="oz_header">
  <table cellpadding="0" cellspacing="0" border="0" width="100%">
    <tr>
      <td align="left"><span id="oz_header_label">{{LOGIN_TITLE}}</span></td>
      <td align="right">&nbsp;
<?php if (ozi_get_config('selector_mode',0)==0) { ?>
      <a href="#" onclick="ozStartAgain();return false;">{{START_AGAIN}}</a>
<?php } ?>      
</td>
    </tr>
  </table>
</div>


<div id="ozpanel_login">
  <script type="text/javascript">
//var oz_lastSelectedService=null;
var _oz_service_panels = new Array();
_oz_service_panels['wa_hotmail']='ozpanel_login_windowslive';
_oz_service_panels['wa_gmail']='ozpanel_login_gmail';
<?php if (!ozi_get_config('facebook_classicmode',FALSE)) {?>_oz_service_panels['is_facebook']='ozpanel_facebook';<?php } ?>
//_oz_service_panels['wa_googleapps']='ozpanel_login_googleapps';

//_oz_service_panels['file_olcsv']='ozpanel_upload';//,ozpanel_olcsv';
//_oz_service_panels['file_oecsv']='ozpanel_upload';//,ozpanel_oecsv';
//_oz_service_panels['file_wmcsv']='ozpanel_upload';//,ozpanel_wmcsv';
//_oz_service_panels['file_tbldif']='ozpanel_upload';//,ozpanel_tbldif';
//_oz_service_panels['bookmark']='ozpanel_bookmark';
//_oz_service_panels['manual']='ozpanel_manual';


function ozLoginInit(src) {

	var opts = document.ozform_select.oz_service.options;
	for (var i=0; i<opts.length; i++) 
	{
		if (opts[i].value==src)
		{		
			document.ozform_select.oz_service.selectedIndex=i;
			break;
		}
	}
	
	//hide('ozpanel_upload,ozpanel_olcsv,ozpanel_oecsv,ozpanel_wmcsv,ozpanel_tbldif,ozpanel_loginpassword,ozpanel_manual,ozpanel_bookmark,ozpanel_dabi');
	ozHide('ozpanel_loginpassword,ozpanel_login_windowslive,ozpanel_login_gmail,ozpanel_facebook');
	var visiblepanels = _oz_service_panels[src];
	if (visiblepanels==undefined)
	{
		ozShow('ozpanel_loginpassword');
		try {document.ozform_login.oz_auth_login.focus();} catch (e) {}
	}
	else
	{
		ozShow(visiblepanels);
	}

//	document.getElementById('oz_header_label').innerHTML=document.ozform_select.oz_service.options[document.ozform_select.oz_service.selectedIndex].innerHTML;
	document.ozform_login.oz_service.value=src;
	
	//Some logins are based on login ID, not email. 
	if (src=='is_blackplanet' || src=='is_hyves' || src=='is_xing' || src=='is_twitter') {
		ozSetDisplayStyle('oz_loginid','inline');
		ozSetDisplayStyle('oz_loginemail','none');
	}
	else {
		ozSetDisplayStyle('oz_loginid','none');
		ozSetDisplayStyle('oz_loginemail','inline');
	}
	
	//Scroll to top of page, otherwise user may miss out some content.
	//window.scroll(0,0);

	ozNotifyViewChange('login');
	if (typeof(ozOnServiceSelected)=='function') ozOnServiceSelected(src);
	
	
}
</script>
  <div id="ozpanel_service_dropdown">
    <form method="post" name="ozform_select" style="margin:0px;" >
<?php echo ozi_render_form_snippet(); ?>
      <table border="0" cellpadding="3" cellspacing="0">
        <tr>
          <td width="120"><span class="oz_field_label">{{LOGIN_NETWORK}}</span></td>
          <td><select name="oz_service" onChange="ozLoginInit(this.options[this.selectedIndex].value)" style="width:250px" class="oz_field_select" id="oz_service_dropdown">
<?php          
$oz_common_webmails_html = '';
$oz_common_webmails_html.=oz_render_service_option('',oz_text('ANY_WEBMAIL'));
$oz_option_count = 0;
$oz_common_webmails_html.=oz_render_service_option(ozi_get_config('prefer_webauth',FALSE)?'wa_gmail':'gmail','GMail');
$oz_common_webmails_html.=oz_render_service_option(ozi_get_config('prefer_webauth',FALSE)?'wa_hotmail':'hotmail','Hotmail');
$oz_common_webmails_html.=oz_render_service_option('yahoo','Yahoo');
$oz_common_webmails_html.=oz_render_service_option('aol','AOL');
$oz_common_webmails_html.=oz_render_service_option('lycos','Lycosmail');
$oz_common_webmails_html.=oz_render_service_option('medotcom','MobileMe (.mac / .me)');
$oz_common_webmails_count = $oz_option_count;

$oz_option_count = 0;
$oz_other_webmails_html = '';
$oz_other_webmails_html.=oz_render_service_option('daumnet','Daum.net');
$oz_other_webmails_html.=oz_render_service_option('emailit','Email.it');
$oz_other_webmails_html.=oz_render_service_option('fastmail','FastMail');
$oz_other_webmails_html.=oz_render_service_option('freenet','Freenet.de');
$oz_other_webmails_html.=oz_render_service_option('gmx','GMX.net');
$oz_other_webmails_html.=oz_render_service_option('icq','IcqMail');
$oz_other_webmails_html.=oz_render_service_option('indiatimes','Indiatimes');
$oz_other_webmails_html.=oz_render_service_option('interia','Interia.pl');
$oz_other_webmails_html.=oz_render_service_option('libero','Libero.it');
$oz_other_webmails_html.=oz_render_service_option('mailru','Mail.ru');
$oz_other_webmails_html.=oz_render_service_option('maildotcom','Mail.com');
$oz_other_webmails_html.=oz_render_service_option('mynet','MyNet');
$oz_other_webmails_html.=oz_render_service_option('naver','Naver.com');
$oz_other_webmails_html.=oz_render_service_option('o2','O2.pl');
$oz_other_webmails_html.=oz_render_service_option('onet','Onet.pl');
$oz_other_webmails_html.=oz_render_service_option('orangees','Orange.es');
$oz_other_webmails_html.=oz_render_service_option('rambler','Rambler');
$oz_other_webmails_html.=oz_render_service_option('rediff','Rediffmail');
$oz_other_webmails_html.=oz_render_service_option('sapo','Sapo.pt');
$oz_other_webmails_html.=oz_render_service_option('sohu','Sohu');
$oz_other_webmails_html.=oz_render_service_option('terra','Terra.es');
$oz_other_webmails_html.=oz_render_service_option('tonlinede','T-Online');
$oz_other_webmails_html.=oz_render_service_option('webde','Web.de');
$oz_other_webmails_html.=oz_render_service_option('wppl','Wp.pl (Wirtualna Polska)');
$oz_other_webmails_html.=oz_render_service_option('yandex','Yandex');
$oz_other_webmails_count = $oz_option_count;

$oz_option_count = 0;
$oz_sn_html = '';
$oz_sn_html.=oz_render_service_option('is_facebook','Facebook');
$oz_sn_html.=oz_render_service_option('is_myspace','MySpace');
$oz_sn_html.=oz_render_service_option('is_twitter','Twitter');
$oz_sn_html.=oz_render_service_option('linkedin','LinkedIn');
$oz_sn_html.=oz_render_service_option('plaxo','Plaxo');
$oz_sn_html.=oz_render_service_option('is_friendster','Friendster');
$inviter = isset($_REQUEST['oz_inviter'])?$_REQUEST['oz_inviter']:NULL;
$orkutEmailSupported = $inviter!==NULL && $inviter->is_service_supported('orkut');
$oz_sn_html.=oz_render_service_option($orkutEmailSupported?'orkut':'is_orkut','Orkut');
//$oz_sn_html.=oz_render_service_option('is_orkut','Orkut');
//$oz_sn_html.=oz_render_service_option('orkut','Orkut (Email)');
$oz_sn_html.=oz_render_service_option('is_hi5','Hi5');
$oz_sn_html.=oz_render_service_option('is_bebo','Bebo');
$oz_sn_html.=oz_render_service_option('is_xing','Xing');
$oz_sn_html.=oz_render_service_option('is_blackplanet','BlackPlanet');
$oz_sn_html.=oz_render_service_option('is_meinvz','MeinVZ');
$oz_sn_html.=oz_render_service_option('is_hyves','Hyves');
$oz_sn_count = $oz_option_count;

?>          

			<?php if ($oz_common_webmails_count>0) { ?>
            <optgroup label="{{DROPDOWN_COMMON_WEBMAILS}}"><?php echo $oz_common_webmails_html ?></optgroup>
            <?php } ?>
              
			<?php if ($oz_other_webmails_count>0) { ?>
            <optgroup label="{{DROPDOWN_OTHER_WEBMAILS}}"><?php echo $oz_other_webmails_html ?></optgroup>
            <?php } ?>

			<?php if ($oz_sn_count>0) { ?>
            <optgroup label="{{DROPDOWN_SOCIAL_NETWORKS}}"><?php echo $oz_sn_html ?></optgroup>
            <?php } ?>
  
            </select>
          </td>
        </tr>
      </table>
    </form>
  </div>
  <?php
//=====================================================================================================================
//LOGIN ID/PASSWORD FORM PANEL
//=====================================================================================================================
?>
  <div id="ozpanel_loginpassword">
    <form method="post" name="ozform_login" onsubmit="return ozOnSubmit();" style="margin:0px;">
<?php echo ozi_render_form_snippet(); ?>
      <input type="hidden" name="oz_state" value="<?php echo htmlentities($_REQUEST['oz_state']) ?>"/>
      <input type="hidden" name="oz_service" value=""/>
      <table border="0" cellpadding="3" cellspacing="0">
        <tr>
          <td width="120"><span class="oz_field_label"  id="oz_loginid">{{LOGIN_ID}}</span><span class="oz_field_label" id="oz_loginemail">{{LOGIN_EMAIL}}</span></td>
          <td><input name="oz_auth_login" type="text" value="<?php echo htmlentities(ozi_get_param('oz_auth_login',''),ENT_COMPAT,'UTF-8') ?>" style="width:250px" class="oz_field_input"/></td>
        </tr>
        <tr>
          <td><span class="oz_field_label">{{LOGIN_PASSWORD}}</span></td>
          <td><input name="oz_auth_password" type="password" style="width:250px" class="oz_field_input"/></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td>{{LOGIN_INSTRUCTIONS}}</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td><input type="submit" name="ozbtn_login" value=" {{LOGIN_FETCH_CONTACTS}} " class="oz_field_button"/></td>
        </tr>
      </table>
    </form>
  </div>
  
  <?php
//=====================================================================================================================
//HOTMAIL WINDOWS LIVE LOGIN PANEL
//=====================================================================================================================
?>
    <form method="post" name="ozform_webauth" onsubmit="return ozOnSubmit();" style="margin:0px">
<?php echo ozi_render_form_snippet(); ?>
      <input type="hidden" name="oz_state" value="<?php echo htmlentities($_REQUEST['oz_state']) ?>"/>
      <input type="hidden" name="oz_service" value=""/>
      <input type="hidden" name="oz_authstr" value=""/>
	<script type="text/javascript">
    function ozAuthCallback(serviceid,authstr)
    {
		ozOnSubmit();	//Show progress bar
		document.ozform_webauth.oz_service.value=serviceid;
		document.ozform_webauth.oz_authstr.value=authstr;
		document.ozform_webauth.submit();
    }
    
    function ozWindowsLiveAuth()
    {
		<?php 
		echo '//'.strtolower(ozi_make_absolute_url(oz_get_current_url(),''))."\r\n";
		if (strpos(strtolower(ozi_make_absolute_url(oz_get_current_url(),'')),'localhost')!==FALSE) { ?>
		alert('Windows Live Login cannot work if the current url is "localhost". Please browse to this page using 127.0.0.1 or a host name');
		<?php } ?>
		var url = 'https://consent.live.com/Delegation.aspx?RU=<?php echo urlencode(ozi_make_absolute_url(oz_get_current_url(),oz_get_resource_path().'auth/windowslive.php')) ?>&ps=Contacts.View&pl=<?php echo (ozi_make_absolute_url(oz_get_current_url(),oz_get_privacy_policy_path())) ?>';
		ozPopUp(url,'oz_auth',650,500);
    }
    function ozGoogleAuth()
    {
		var url = 'https://www.google.com/accounts/AuthSubRequest?session=0&secure=0&scope=http%3A%2F%2Fwww%2Egoogle%2Ecom%2Fm8%2Ffeeds%2F&next=<?php echo urlencode(ozi_make_absolute_url(oz_get_current_url(),oz_get_resource_path().'auth/google.php')) ?>';
		ozPopUp(url,'oz_auth',650,500);
    }
    function ozGoogleAppsAuth()
    {
		var domain = document.ozform_googleapps.gapps_domain.value;
		var url = 'https://www.google.com/accounts/AuthSubRequest?session=0&secure=0&scope=http%3A%2F%2Fwww%2Egoogle%2Ecom%2Fm8%2Ffeeds%2F&next=<?php echo urlencode(ozi_make_absolute_url(oz_get_current_url(),oz_get_resource_path().'auth/google.php')) ?>&hd='+escape(domain);
		ozPopUp(url,'oz_auth',650,500);
    }
    </script>
    </form>
		  

  <div id="ozpanel_login_windowslive" style="display:none;">
	<form style="margin:0px">
<?php echo ozi_render_form_snippet(); ?>
   {{LOGIN_HOTMAIL_INSTRUCTIONS}}<br/><br/>
      <input type="submit" name="ozbtn_wll" value="{{LOGIN_HOTMAIL_BUTTON}}" onclick="ozWindowsLiveAuth();return false;"/>
    </form>
  </div>
  <div id="ozpanel_login_gmail" style="display:none">
 	<form style="margin:0px" name="ozform_googleapps">
<?php echo ozi_render_form_snippet(); ?>
    {{LOGIN_GMAIL_INSTRUCTIONS}}<br/><br/>
      <input type="submit" name="ozbtn_gmail" value="{{LOGIN_GMAIL_BUTTON}}" onclick="ozGoogleAuth();return false;"/>
      
    <br/><br/>
    <br/><br/>
    {{LOGIN_GOOGLEAPPS_INSTRUCTIONS}}<br/><br/>
      {{LOGIN_GOOGLEAPPS_DOMAIN}} <input type="text" name="gapps_domain" size="15" class="oz_field_input"/> {{LOGIN_GOOGLEAPPS_DOMAIN_EXAMPLE}} <br/><br/>
      <input type="submit" name="ozbtn_googleapps" value="{{LOGIN_GOOGLEAPPS_BUTTON}}" onclick="ozGoogleAppsAuth();return false;"/>
    </form>    
  </div>
  <div id="ozpanel_facebook" style="display:none;">
<?php
	global $_OZINVITER_CALLBACKS;
	$func = $_OZINVITER_CALLBACKS['get_invite_message']	;
	$msg = $func(NULL,NULL,NULL);
	//$msg = oz_get_invite_message();
	$url = $msg['url'];
	$title = $msg['subject'];
	//$text_body = str_replace('{PERSONALMESSAGE}','',$msg['text_body']);
	//$text_body = '';
?>    
    
   {{SHARE_FACEBOOK_INSTRUCTIONS}}<br/><br/>
	<form style="margin:0px">
   <input type="button" onclick="ozPopUp('http://www.facebook.com/sharer.php?u=<?php echo urlencode($url) ?>&amp;t=<?php echo urlencode($title) ?>','oz_auth',650,600);return false;" value="{{SHARE_LINK}}">
   </form>
  </div>

</div>
<div style="display:none">Powered by <a href="http://www.octazen.com" target="_blank">Octazen Solutions Invite Engine</a></div>
<!--
<script type="text/javascript">

/*
function ozUpdateVisibility()
{
	sel = document.ozform_select.oz_service;
	ozLoginInit(sel.options[sel.selectedIndex].value);
	clearTimeout(oz_timeout1);
}
//Enabling this seems to cause a error on IE where we try to set focus on a field which is not yet visible.
//(as the whole login form itself isn't visible during the first load)

oz_timeout1 = setTimeout("ozUpdateVisibility()",0);
*/
</script>
-->